//
//  TNBNotificationDefine.h
//  ToonBrowser
//
//  Created by kevinma on 15/11/23.
//  Copyright © 2015年 kevinma. All rights reserved.
//

#ifndef TNBNotificationDefine_h
#define TNBNotificationDefine_h

#pragma mark - NSNotification
#define TNBNOTIFICATION_GETWEBVIEW                              @"TNBNOTIFICATION_GETWEBVIEW"
#define TNBNOTIFICATION_PLUGINDOWNLOADED                        @"TNBNOTIFICATION_PLUGINDOWNLOADED"
#define TNBNOTIFICATION_DOWNLOAD                                @"TNBNOTIFICATION_DOWNLOAD"
#define TNBNOTIFICATION_INSTALLOVER                             @"TNBNOTIFICATION_INSTALLOVER"
#define TNBNOTIFICATION_CREATECARD                              @"TNACreateSelfCardController"
#define TNBNOTIFICATION_GOFRAME                                 @"TAK_scene"
#define TNBNOTIFICATION_CREATECARD_COMPLETE                     @"CREATECARD_COMPLETE"
#define TNBNOTIFICATION_CREATESHOWBLOCK_COMPLETE                @"CREATESHOWBLOCK_COMPLETE"
#define TNBNOTIFICATION_DEPLOY                                  @"TNBNOTIFICATION_DEPLOY"
#define TNBNOTIFICATION_NAVIGATIONBARTITLE                      @"TNBNOTIFICATION_NAVIGATIONBARTITLE"

#define TNBNOTIFICATION_AUDIOPLAYERDIDSTARTPLAYING              @"TNBNOTIFICATION_AUDIOPLAYERDIDSTARTPLAYING"
#define TNBNOTIFICATION_AUDIOPLAYERDIDFINISHPLAYING             @"TNBNOTIFICATION_AUDIOPLAYERDIDFINISHPLAYING"
#define TNBNOTIFICATION_AUDIOPLAYERDECODEERRORDIDOCCUR          @"TNBNOTIFICATION_AUDIOPLAYERDECODEERRORDIDOCCUR"
#define SHARESTANDARD_NOMARLITEM_CLICK_NOTIFICATION             @"SHARESTANDARD_NOMARLITEM_CLICK_NOTIFICATION"

#endif /* TNBNotificationDefine_h */
